### ISSUE TITLE
Refactor App to use React Router

### ISSUE THREAD

**Issue by alexthompson207** [alexthompson207/current-climate#18]
- Use Router to change url path based on articles id
- maybe use switch?
- try using redirect to direct article URL to NYT article

**Comment by Serjeel-Ranjan-911** [comment]
is this error in my system only?  @alexthompson207 
```
Failed to compile.

./src/components/Header/Header.js
Cannot find file: 'header.css' does not match the corresponding name on disk: '.\src\components\Header\Header.css'.
```
this is coming for all css files.
